bramanta/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('campaign/', campaignPage, name = 'campaignPage'),
    path('browse/', browseCampaign, name = 'browseCampaign'),
]

hamri/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('createCampaign', createCampaign, name = 'createCampaign'),
    path('savecampaign', savecampaign, name = 'savecampaign')
]

homepage/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),]

signin/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register', register, name = 'signin'),
    
]

tugas1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('homepage.urls', 'homepage'), namespace='homepage')),
    path('bramanta/', include(('bramanta.urls', 'bramanta'), namespace='bramanta')),
	path('hamri/', include(('hamri.urls', 'hamri'), namespace='hamri')),
    path('signin/', include(('signin.urls', 'signin'), namespace='signin')),
]

bramanta/models.py
from django.db import models

# Create your models here.

hamri/models.py
from django.db import models

# Create your models here.

class Campaign(models.Model):
	Project_name = models.TextField(max_length = 40)
	Goal = models.TextField(max_length = 40)
	Donation_end_date= models.DateField(max_length = 50)
	Description = models.TextField(max_length = 250)
	image=models.FileField(upload_to = 'static/', default = 'static/None/no-img.jpg')

homepage/models.py
from django.db import models

signin/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class daftar(models.Model):
    namadepan = models.CharField(max_length = 100)
    namabelakang = models.CharField(max_length = 100)
    alamat = models.CharField(max_length = 100)
    email = models.EmailField(null = True,blank = True)
    tgl = models.DateField()
    password = models.CharField(max_length = 32)
    confirm = models.CharField(max_length = 32)

hamri/forms.py
from django import forms

from .models import Campaign

class PostCampaign(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ('Project_name', 'Goal', 'Donation_end_date', 'Description','image')

# class form_sub(forms.Form):
# 	Project_name = forms.CharField(label='', required=True, max_length=40, widget=forms.TextInput(attrs=title_attrs))
#     Goal = forms.CharField(label='', required=True, max_length=40, widget=forms.TextInput(attrs=title_attrs))
# 	Donation_end_date = forms.DateField(label='', required=True, max_length=50, widget=forms.TextInput(attrs=title_attrs))
# 	Description = forms.CharField(label='', required=True, max_length=250, widget=forms.TextInput(attrs=title_attrs))

homepage/forms.py
from django import forms

class form_sub(forms.Form):
    nama_depan= forms.CharField(label= "First Name")
    nama_belakang= forms.CharField(label= "Last Name")
    alamat = forms.CharField(label = "Alamat")
    email = forms.CharField(label = "Email")
    password=forms.CharField(label= "Password")
    confirm=forms.CharField(label= "Password")

signin/forms.py
from django import forms
import datetime

YEARS = [x for x in range(1940,2021)]
class SignIn(forms.Form):
	nama_depan = forms.CharField(label='Nama depan',max_length=100)
	nama_belakang = forms.CharField(max_length = 100)
	alamat = forms.CharField(max_length  =100)
	tgl = forms.DateField(label='Tanggal Lahir',widget=forms.SelectDateWidget(years=YEARS))
	email = forms.EmailField(label='Email',max_length=254)
	password = forms.CharField(label='Password',max_length=100,widget=forms.PasswordInput)
	confirm = forms.CharField(label='Confirm Password',max_length=100,widget=forms.PasswordInput)

bramanta/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from hamri.models import Campaign
# Create your views here.
response = {}
def campaignPage(request):
	return render(request, 'campaignPage.html')

def browseCampaign(request):
	campaigns = Campaign.objects.all()
	response['campaigns'] = campaigns
	html = 'browseCampaign.html'
	return render(request, html, response)

hamri/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Campaign
from .forms import PostCampaign

# Create your views here.
response = {}

def createCampaign(request):
	campaigns = Campaign.objects.all()
	response['campaigns'] = campaigns

	html = 'Create-Campaign.html'
	return render(request, html, response)

def savecampaign(request):
	form = PostCampaign(request.POST or None)
	if(request.method == 'POST'):
		response['Project_name'] = request.POST['Project_name']
		response['Goal'] = request.POST['Goal']
		response['Donation_end_date'] = request.POST['Donation_end_date']
		response['Description'] = request.POST['Description']
		response['image']=request.POST['image']
		myCampaign = Campaign(Project_name=response['Project_name'], Goal=response['Goal'], Donation_end_date=response['Donation_end_date'], Description=response['Description'],image=response['image'])
		myCampaign.save()
		return HttpResponseRedirect('/')
	else:
		return HttpResponseRedirect('/')

homepage/views.py
from django.shortcuts import render
from .forms import form_sub
from django.http import HttpResponseRedirect
# Create your views here.
def index(request):
    return render(request, 'home.html')

signin/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import SignIn
from .models import daftar
from datetime import datetime
# Create your views here.
def register(request):
	
	account = daftar.objects.all().values()
	
	if request.method == 'POST':
		form = SignIn(request.POST)
		if form.is_valid():
			account = daftar()
			account.namadepan = form.cleaned_data['namadepan']
			account.namabelakang  =form.cleaned_dara['namabelakangs']
			account.tgl = form.cleaned_data['tgl']
			account.alamat = form.cleaned_dara['alamat']
			account.email = form.cleaned_data['email']
			account.password = form.cleaned_data['password']
			account.date = datetime.now()
			account.save()
			return HttpResponseRedirect('register')
	else:
		form = SignIn()
	
	response = {
        'form' : form,
        'account' : account,
	}
	
	return render(request, "index.html", response)

bramanta/templates/browseCampaign.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SinarPerak</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
    <link href="navbar.html" rel="import">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{%block content%}{%include 'navbar.html'%}{%endblock%}  
<div class="container"> 
    {% for data in campaigns %}
    <div class="row">
        <div class="col-sm">
            <p>{{ data.Project_name }}</p>
        </div>
        <div class="col-sm">
            <p>{{ data.Description }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{%include 'footer.html'%}
</body>
</html>

bramanta/templates/campaignPage.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SinarPerak</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
    <link href="navbar.html" rel="import">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{%block content%}{%include 'navbar.html'%}{%endblock%}  
<div class="container"> 
    <img src="https://natgeo.imgix.net/subjects/headers/ND%20header%20(1).jpg?auto=compress,format&w=1920&h=960&fit=crop/200x100" class="img-thumbnail" alt="Responsive image">
    <br>
    <br>
    <div class="row">
        <div class="col-md" style="background-color:#80475E; color:white">
            <p>DESCRIPTION :</p>
        </div>
        <p>apa kek</p>
    </div>
    <div class="row">
        <div class="col-md" style="background-color:#80475E; color:white">
            <p>DONATION GOALS :</p>
        </div>
        <div class="col-md">
            <p>lalala</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" style="background-color:#80475E; color:white">
            <p>END DATE :</p>
        </div>
        <div class="col-md">
            <p>lalala</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" style="background-color:#80475E; color:white">
            <p>CONTACTS :</p>
        </div>
        <div class="col-md">
            <p>lalala</p>
        </div>
    </div>
    <br>
    <button type="button" class="btn btn-primary btn-lg" style="background-color:#80475E;display: block;margin-left: auto;margin-right: auto;">DONATE</button>      
    <br>
</div>
{%include 'footer.html'%}
</body>
</html>

bramanta/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url 'signin:signin' %}">Sign up</a></p>
      <p class="ab"><a href="{% url 'bramanta:browseCampaign' %}">Donate</a></p>
      <p class="ab"><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></p>
      
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

bramanta/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak">
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'homepage:index' %}">Home</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="{% url 'bramanta:browseCampaign' %}">Browse Campaign</a></li>
      <li><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'signin:signin' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    </ul>
  </div>
</nav>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}

hamri/templates/Create-Campaign.html
{%load static%}
<!DOCTYPE html>
<!-- Homepage (hello.html), footer ,and header by Jeremy -->
<html>
<body>
<head>
<!DOCTYPE html>
<html lang="en">
<head>
<title>
  SinarPerak
</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
  <link href="navbar.html" rel="import">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color: #80475E;color: white">
{%block content%}{%include 'navbar.html'%}{%endblock%}
<section style="margin-left: 30px;margin-top: 75px">
<form action="{% url 'hamri:savecampaign' %}" method="POST">
  {% csrf_token %}
  Project_name:<br>
  <input type="text" name="Project_name" value="Project_name" style="color:#80475E ">
  <br><br>
  Goal:<br>
  <input type="text" name="Goal" value="Goal" style="color:#80475E ">
  <br><br>
  Donation end date:<br>
  <input type="date" name="Donation_end_date" value="Donation_end_date" style="color:#80475E ">
  <br><br>
  Description:<br>
  <textarea name="message" rows="10" cols="30" style="color:#80475E ">Help each other by donating or join the campaign!</textarea>
  <br><br>
  <input type="file" name="image" accept="image/*">
  <br>
  <input type="submit" value="Submit" style="color:#80475E ">
</form>
</section>
<br>
<br>
<br>


{%include 'footer.html'%}
</body>
</html>

hamri/templates/create.html
{%load static%}
<!DOCTYPE html>
<!-- Homepage (hello.html), footer ,and header by Jeremy -->
<html>
<head>
<!DOCTYPE html>
<html lang="en">
<head>
<title>
  WEBSITE CUY
</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
  <link href="navbar.html" rel="import">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{%block content%}{%include 'navbar.html'%}{%endblock%}
{%include 'footer.html'%}
</body>
</html>

hamri/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url 'bramanta:browseCampaign' %}">Donate</a></p>
      <p class="ab"><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></p>
      <p class="ab"><a href="{% url 'signin:register' %}">Sign up!</a></p>
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

hamri/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak">
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'homepage:index' %}">Home</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="{% url 'bramanta:browseCampaign' %}">Browse Campaign</a></li>
      <li><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'signin:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    </ul>
  </div>
</nav>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}

homepage/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url 'bramanta:browseCampaign' %}">Donate</a></p>
      <p class="ab"><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></p>
      <p class="ab"><a href="{% url 'signin:register' %}">Sign up!</a></p>
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

homepage/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak">
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'homepage:index' %}">Home</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="{% url 'bramanta:browseCampaign' %}">Browse Campaign</a></li>
      <li><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'signin:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    </ul>
  </div>
</nav>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}

homepage/templates/thanks.html
{%load static%}
<!-- Home page (home.html), footer ,and header by Jeremy -->
<!DOCTYPE html>
<html>
<head>
<!DOCTYPE html>
<html lang="en">
<head>
<title>
  WEBSITE CUY
</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
  <link href="navbar.html" rel="import">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{%block content%}{%include 'navbar.html'%}{%endblock%}

<h1 style="padding-top: 5%; font-size: 25px ;text-align: center; color:#80475E"><br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>Thank you for signing up! We hope you can help others who needs!<br>
	<br>
	<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br></h1>
{%include 'footer.html'%}
</body>
</html>

signin/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url 'bramanta:browseCampaign' %}">Donate</a></p>
      <p class="ab"><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></p>
      <p class="ab"><a href="{% url 'signin:register' %}"">Sign up!</a></p>
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

signin/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'sinarperaklogo.png' %}" alt="SinarPerak">
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'homepage:index' %}">Home</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="{% url 'bramanta:browseCampaign' %}">Browse Campaign</a></li>
      <li><a href="{% url 'hamri:createCampaign' %}">Create Campaign!</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'signin:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    </ul>
  </div>
</nav>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}